window.PORTFOLIO_DATA = {
  categories: [
    { id: "all", zh: "全部", en: "ALL" },
    { id: "authored", zh: "自主发起", en: "SELF-INITIATED" },
    { id: "commissioned", zh: "合作与委托", en: "COLLABORATION / COMMISSION" }
  ],
  projects: [
    { id:"unwritten-rain", no:"01", title:"未落款的雨", year:"2026", category:"authored", relation:"原创音乐合作 / 毕业季共创", type:"华为 MatePad Pro Max 音乐叙事短片", role:"导演 / 摄影 / 后期", summary:"毕业典礼散场之后，把青春里淋过的雨写成一首歌。\n作品以雨夜、离别与未完成的署名为线索，将原创音乐、校园记忆与产品创作场景组织成完整叙事。", result:"抖音单条播放超 6 万，点赞约 2500；华为高校花粉挑战赛复赛入围。", link:"https://v.douyin.com/BUnsKCL3WsU/", visual:"rain", cover:"assets/projects/unwritten-rain/cover-title.png", media:[
      { src:"assets/projects/unwritten-rain/still-02.jpg", alt:"《未落款的雨》湿润路面上的落花", label:"FILM STILL / 02" },
      { src:"assets/projects/unwritten-rain/still-03.jpg", alt:"《未落款的雨》剧场内的舞台远景", label:"FILM STILL / 03" },
      { src:"assets/projects/unwritten-rain/still-05.jpg", alt:"《未落款的雨》创作者在剧场记录", label:"FILM STILL / 05" },
      { src:"assets/projects/unwritten-rain/still-06.jpg", alt:"《未落款的雨》大学生日回忆场景", label:"FILM STILL / 06" },
      { src:"assets/projects/unwritten-rain/still-08.jpg", alt:"《未落款的雨》礼堂散场后的空间", label:"FILM STILL / 08" },
      { src:"assets/projects/unwritten-rain/still-10.jpg", alt:"《未落款的雨》雨滴落在平板屏幕", label:"FILM STILL / 10" },
      { src:"assets/projects/unwritten-rain/still-11.jpg", alt:"《未落款的雨》校园雨夜中的行人", label:"FILM STILL / 11" },
      { src:"assets/projects/unwritten-rain/still-12.jpg", alt:"《未落款的雨》雨夜里的移动创作", label:"FILM STILL / 12" },
      { src:"assets/projects/unwritten-rain/still-14.jpg", alt:"《未落款的雨》散场后的雨中倒影", label:"FILM STILL / 14" }
    ] },
    { id:"beyond-wide", no:"02", title:"比你以为的阔", year:"2026", category:"authored", relation:"联合发起 / 校园品牌共创", type:"华为 Pura X View 校园创意短片", role:"导演 / 摄影 / 后期", summary:"把开学理解为一次重新发现自我的过程：笔写下新故事，镜头转向自己，校园空间也被重新打开。\n项目与泉州师范学院图书馆合作，以轻叙事串联产品体验与新生情绪。", result:"多平台累计播放约 10 万，点赞约 1700。", links:[{ href:"https://v.douyin.com/5GV7S-55UQc/", label:"抖音发布" },{ href:"https://weixin.qq.com/sph/AICrBkKl1c", label:"图书馆视频号发布" }], visual:"wide", cover:"assets/projects/beyond-wide/still-01.jpg", media:[
      { src:"assets/projects/beyond-wide/still-02.jpg", alt:"《比你以为的阔》打开笔记本电脑", label:"FILM STILL / 02" },
      { src:"assets/projects/beyond-wide/still-03.jpg", alt:"《比你以为的阔》图书馆书写场景", label:"FILM STILL / 03" },
      { src:"assets/projects/beyond-wide/still-05.jpg", alt:"《比你以为的阔》图书馆空间转场", label:"FILM STILL / 05" },
      { src:"assets/projects/beyond-wide/still-06.jpg", alt:"《比你以为的阔》小廖人物建立镜头", label:"FILM STILL / 06" },
      { src:"assets/projects/beyond-wide/still-07.jpg", alt:"《比你以为的阔》校园活动入口记录", label:"FILM STILL / 07" },
      { src:"assets/projects/beyond-wide/still-10.jpg", alt:"《比你以为的阔》小刘毕业设计场景", label:"FILM STILL / 10" },
      { src:"assets/projects/beyond-wide/still-11.jpg", alt:"《比你以为的阔》手机与手写笔操作", label:"FILM STILL / 11" },
      { src:"assets/projects/beyond-wide/still-13.jpg", alt:"《比你以为的阔》镜头转向自己", label:"FILM STILL / 13" },
      { src:"assets/projects/beyond-wide/still-14.jpg", alt:"《比你以为的阔》校园友情出演", label:"FILM STILL / 14" },
      { src:"assets/projects/beyond-wide/still-15.jpg", alt:"《比你以为的阔》片尾创作署名", label:"FILM STILL / 15" }
    ] },
    { id:"liancheng", no:"03", title:"早晚得来", year:"2025", category:"commissioned", relation:"文旅委托 / 目的地传播", type:"冠豸山 5A 景区国庆宣传片", role:"导演 / 摄影 / 后期 / 前期对接与场地协调", summary:"《早晚得来》从现代生活“总在赶时间”的共同经验切入，用“一早一晚”的结构，把早餐、山水、古村、非遗与夜市串成一条可以感知的连城旅行线索。\n项目落地于冠豸山景区获评国家 5A 级旅游景区后的首个国庆假期。片名既对应从清晨到夜晚的生活节奏，也带着“迟早都得来”的邀请，让节日传播不止于罗列景点。\n我更希望观众看见一座城的生活温度与情感节奏：连城不仅值得抵达，也是一处能让人放慢脚步、愿意停留下来的地方。", result:"多平台累计播放约 13 万；获福建省第十二届大学生影像大赛重大主题类一等奖。", link:"https://weixin.qq.com/sph/AdmONtI6SI", linkLabel:"观看原片", visual:"daynight", cover:"assets/projects/liancheng/cover-title.jpg", media:[
      { src:"assets/projects/liancheng/still-01.jpg", alt:"夜市摊位中的晚餐现场", label:"FILM STILL / 夜市" },
      { src:"assets/projects/liancheng/still-02.jpg", alt:"炉火上的砂锅与升起的蒸汽", label:"FILM STILL / 炉火" },
      { src:"assets/projects/liancheng/still-03.jpg", alt:"连城街巷的全景球形画面", label:"FILM STILL / 连城街巷" },
      { src:"assets/projects/liancheng/still-04.jpg", alt:"油锅旁刚出炉的灯盏糕", label:"FILM STILL / 早餐" },
      { src:"assets/projects/liancheng/still-05.jpg", alt:"早餐铺主理人站在店门前", label:"FILM STILL / 店主" },
      { src:"assets/projects/liancheng/still-06.jpg", alt:"培田古村落屋顶航拍", label:"FILM STILL / 培田古村" },
      { src:"assets/projects/liancheng/still-07.jpg", alt:"金色稻田中的人物", label:"FILM STILL / 田野" },
      { src:"assets/projects/liancheng/still-08.jpg", alt:"冠豸山花丛间的人物肖像", label:"FILM STILL / 冠豸山" },
      { src:"assets/projects/liancheng/still-09.jpg", alt:"九龙湖水坝航拍", label:"FILM STILL / 九龙湖" },
      { src:"assets/projects/liancheng/still-10.jpg", alt:"夜市中品尝砂锅鱼汤", label:"FILM STILL / 夜味" },
      { src:"assets/projects/liancheng/still-11.jpg", alt:"围桌晚餐的全景球形画面", label:"FILM STILL / 围桌" },
      { src:"assets/projects/liancheng/still-12.jpg", alt:"水南桥夜景与人物", label:"FILM STILL / 水南桥" },
      { src:"assets/projects/liancheng/still-13.jpg", alt:"姑田游大龙现场中的人物", label:"FILM STILL / 游大龙" },
      { src:"assets/projects/liancheng/still-14.jpg", alt:"四角井前烟花与游龙人群", label:"FILM STILL / 烟火" },
      { src:"assets/projects/liancheng/still-15.jpg", alt:"人物背对镜头观看烟花", label:"FILM STILL / 仰望" },
      { src:"assets/projects/liancheng/still-16.jpg", alt:"用手机记录培田古村巷道", label:"FILM STILL / 记录" },
      { src:"assets/projects/liancheng/still-17.jpg", alt:"连城县城夜景与烟花航拍", label:"FILM STILL / 早晚都快乐" }
    ] },
    { id:"houapo", no:"04", title:"有味有爱有乡愁", year:"2026", category:"commissioned", relation:"商业委托 / 品牌内容", type:"侯阿婆肉粽端午品牌人文宣传片", role:"摄影 / 后期", summary:"以一枚泉州烧肉粽为入口，回到侯阿婆肉粽近半个世纪的传承现场。\n六分钟成片从原料、手艺、三代经营与海外乡愁切入，让地方味道成为品牌历史与闽南情感的共同载体。", result:"泉州晚报视频号单平台播放约 5 万。", link:"https://weixin.qq.com/sph/Aohd4RGF4m", visual:"taste", cover:"assets/projects/houapo/cover.jpg", media:[] },
    { id:"sibao", no:"05", title:"四堡雕版印刷", year:"2025", category:"authored", relation:"文化记录 / 非遗影像", type:"非遗文化纪录片", role:"导演 / 脚本 / 主摄影 / 主后期", summary:"走进连城四堡，从地方书坊遗迹、雕版工艺与历史线索出发，重新靠近一项延续数百年的传统印刷技艺。\n作品不试图完整复述它的全部历史，而以木版、刻刀、墨色和纸张构成视觉骨架，用传承人的经验补足时间的厚度，也把家族协作、乡村文脉与时代变迁带进画面。\n我希望让刀刻与墨香重新进入今天的观看，使四堡雕版印刷不只作为知识被介绍，也成为仍可被感知、被理解的地方文化记忆。", result:"福建省第十二届大学生影像大赛创意类二等奖；第八届金鹄青年电影周暨原创影像大赛文旅单元入围。", link:"https://weixin.qq.com/sph/AqOHkssWHj", visual:"print", cover:"assets/projects/sibao/cover.jpg", media:[
      { src:"assets/projects/sibao/still-16.jpg", alt:"暗部空间剪影", label:"FILM STILL / 16" },
      { src:"assets/projects/sibao/still-19.jpg", alt:"村民打开木门", label:"FILM STILL / 19" },
      { src:"assets/projects/sibao/still-10.jpg", alt:"书坊灯笼", label:"FILM STILL / 10" },
      { src:"assets/projects/sibao/still-13.jpg", alt:"木版字迹特写", label:"FILM STILL / 13" },
      { src:"assets/projects/sibao/still-17.jpg", alt:"雕版与刻刀静物", label:"FILM STILL / 17" },
      { src:"assets/projects/sibao/still-18.jpg", alt:"传承人雕版工作场景", label:"FILM STILL / 18" },
      { src:"assets/projects/sibao/still-11.jpg", alt:"手触雕版纹理", label:"FILM STILL / 11" },
      { src:"assets/projects/sibao/still-12.jpg", alt:"雕刻工艺近景", label:"FILM STILL / 12" },
      { src:"assets/projects/sibao/still-04.jpg", alt:"古籍与木桌", label:"FILM STILL / 04" },
      { src:"assets/projects/sibao/still-07.jpg", alt:"古樟树与刀痕文字", label:"FILM STILL / 07" },
      { src:"assets/projects/sibao/still-08.jpg", alt:"古樟树旁的人物", label:"FILM STILL / 08" },
      { src:"assets/projects/sibao/still-09.jpg", alt:"古樟与古建筑", label:"FILM STILL / 09" },
      { src:"assets/projects/sibao/still-02.jpg", alt:"书坊建筑中的人物", label:"FILM STILL / 02" },
      { src:"assets/projects/sibao/still-21.jpg", alt:"古建筑屋顶俯拍", label:"FILM STILL / 21" },
      { src:"assets/projects/sibao/still-24.jpg", alt:"书院天井俯拍", label:"FILM STILL / 24" },
      { src:"assets/projects/sibao/still-14.jpg", alt:"村落书院与水塘", label:"FILM STILL / 14" },
      { src:"assets/projects/sibao/still-22.jpg", alt:"村落航拍与田野", label:"FILM STILL / 22" },
      { src:"assets/projects/sibao/still-06.jpg", alt:"四堡村落航拍", label:"FILM STILL / 06" },
    ] },
    { id:"xinquan-fireworks", no:"06", title:"新泉烧炮", year:"2025", category:"authored", relation:"田野记录 / 非遗影像", type:"闽西客家民俗纪录片", role:"导演 / 摄影 / 航拍 / 后期", summary:"《新泉烧炮》沿着闽西新泉正月十四至十五的仪式次序，记录制炮、迎神、巡游、祭祀与烧炮，呈现这项延续多代的客家民俗如何由村民共同完成。\n相比只追逐炮火的热闹，我更关注火光、烟雾、队伍与神轿背后的人：他们的神情、动作、秩序，以及温泉边集体劳作所维系的村落关系。\n作品以贴近现场的方式补充地方影像记录，让仪式从节庆奇观回到共同生活，也记录年轻一代如何参与、记住并继续讲述它。", result:"获福建省第十二届大学生影像大赛重大主题类一等奖。", link:"https://weixin.qq.com/sph/AA48agKVhh", linkLabel:"观看原片", visual:"fire", cover:"assets/projects/xinquan-fireworks/cover.jpg", media:[
      { src:"assets/projects/xinquan-fireworks/still-01.jpg", alt:"群山环抱的新泉村落航拍", label:"FILM STILL / 村落" },
      { src:"assets/projects/xinquan-fireworks/still-02.jpg", alt:"村民手工制作炮竹的手部特写", label:"FILM STILL / 制炮" },
      { src:"assets/projects/xinquan-fireworks/still-03.jpg", alt:"院落中制作炮竹的俯拍画面", label:"FILM STILL / 制炮院落" },
      { src:"assets/projects/xinquan-fireworks/still-04.jpg", alt:"村民在白墙前舂制炮料", label:"FILM STILL / 舂料" },
      { src:"assets/projects/xinquan-fireworks/still-05.jpg", alt:"制炮工具与红色片名构成的静物画面", label:"FILM STILL / 制炮器具" },
      { src:"assets/projects/xinquan-fireworks/still-06.jpg", alt:"河流与村落交汇的新泉航拍", label:"FILM STILL / 新泉" },
      { src:"assets/projects/xinquan-fireworks/still-07.jpg", alt:"祠堂内香火与人群", label:"FILM STILL / 祠堂" },
      { src:"assets/projects/xinquan-fireworks/still-08.jpg", alt:"祠堂鼓前围聚的村民", label:"FILM STILL / 聚集" },
      { src:"assets/projects/xinquan-fireworks/still-09.jpg", alt:"正月初六的仪式段落画面", label:"FILM STILL / 正月初六" },
      { src:"assets/projects/xinquan-fireworks/still-11.jpg", alt:"祠堂中进行抽签仪式的村民", label:"FILM STILL / 抽签" },
      { src:"assets/projects/xinquan-fireworks/still-12.jpg", alt:"烛火旁凝视仪式的年轻人", label:"FILM STILL / 烛火" },
      { src:"assets/projects/xinquan-fireworks/still-13.jpg", alt:"村民围绕供桌参与仪式", label:"FILM STILL / 共祭" },
      { src:"assets/projects/xinquan-fireworks/still-15.jpg", alt:"云雾覆盖群山与村落的正月十五", label:"FILM STILL / 正月十五" },
      { src:"assets/projects/xinquan-fireworks/still-16.jpg", alt:"村民以烛火点燃长香", label:"FILM STILL / 点香" },
      { src:"assets/projects/xinquan-fireworks/still-17.jpg", alt:"三太祖师出游队伍穿行村落", label:"FILM STILL / 出游" },
      { src:"assets/projects/xinquan-fireworks/still-18.jpg", alt:"炮烟升腾时恭迎圣驾的俯拍画面", label:"FILM STILL / 迎驾" },
      { src:"assets/projects/xinquan-fireworks/still-19.jpg", alt:"仪式队伍沿山路前行的航拍", label:"FILM STILL / 巡游" },
      { src:"assets/projects/xinquan-fireworks/still-20.jpg", alt:"炮烟中的街巷与围观人群", label:"FILM STILL / 炮烟" },
      { src:"assets/projects/xinquan-fireworks/still-21.jpg", alt:"神轿队伍穿过新泉旧巷", label:"FILM STILL / 过巷" },
      { src:"assets/projects/xinquan-fireworks/still-23.jpg", alt:"一家人在雨伞下观看仪式", label:"FILM STILL / 家人" },
      { src:"assets/projects/xinquan-fireworks/still-24.jpg", alt:"村民在供桌前整理祭品", label:"FILM STILL / 传承" }
    ] },
    { id:"ball-astronomy", no:"07", title:"一个球的故事", year:"2025", category:"authored", relation:"校园记录 / 社团记忆", type:"连城一中天文社纪录片", role:"导演 / 摄影 / 后期", summary:"从天文台里的一架望远镜出发，回看连城一中天文社自 2003 年成立以来的观测、科普与社团传承。\n影片把旧照片、历届成员口述、夜间观测和社员拍摄的深空影像交织在一起，让一颗看似冰冷的仪器，成为一群年轻人持续仰望星空的共同记忆。", result:"完成社团历史、成员口述与天文观测素材的影像整理，记录一代代学生共同延续的校园天文实践。", visual:"cosmic", cover:"assets/projects/ball-astronomy/cover.jpg", media:[
      { src:"assets/projects/ball-astronomy/still-01.jpg", alt:"天文台穹顶内的大型望远镜", label:"FILM STILL / 望远镜" },
      { src:"assets/projects/ball-astronomy/still-02.jpg", alt:"天文社成员在楼顶调试望远镜", label:"FILM STILL / 调试" },
      { src:"assets/projects/ball-astronomy/still-03.jpg", alt:"天文台穹顶与观测中的社员", label:"FILM STILL / 天文台" },
      { src:"assets/projects/ball-astronomy/still-04.jpg", alt:"三位天文社成员在观测室交流", label:"FILM STILL / 社员" },
      { src:"assets/projects/ball-astronomy/still-05.jpg", alt:"2020 年社员使用望远镜观测的档案画面", label:"ARCHIVE / 2020" },
      { src:"assets/projects/ball-astronomy/still-06.jpg", alt:"夜间楼顶的望远镜观测现场", label:"FILM STILL / 夜间观测" },
      { src:"assets/projects/ball-astronomy/still-07.jpg", alt:"望远镜拍摄的月球表面", label:"ASTROGRAPHY / 月球" },
      { src:"assets/projects/ball-astronomy/still-08.jpg", alt:"学生透过大型望远镜观察星空", label:"ARCHIVE / 观测" },
      { src:"assets/projects/ball-astronomy/still-09.jpg", alt:"穹顶内仰望星空的望远镜剪影", label:"FILM STILL / 穹顶" },
      { src:"assets/projects/ball-astronomy/still-10.jpg", alt:"学生围绕大型望远镜参加科普活动", label:"ARCHIVE / 科普活动" },
      { src:"assets/projects/ball-astronomy/still-11.jpg", alt:"中学生在夜间操作望远镜", label:"ARCHIVE / 操场观测" },
      { src:"assets/projects/ball-astronomy/still-12.jpg", alt:"天文社拍摄的猎户座大星云", label:"ASTROGRAPHY / 猎户座大星云" },
      { src:"assets/projects/ball-astronomy/still-13.jpg", alt:"天文社拍摄的银河与校园屋顶", label:"ASTROGRAPHY / 银河" },
      { src:"assets/projects/ball-astronomy/still-14.jpg", alt:"天文社拍摄的仙女座星系", label:"ASTROGRAPHY / 仙女座星系" },
      { src:"assets/projects/ball-astronomy/still-15.jpg", alt:"第二届天文社成员在穹顶前合影", label:"ARCHIVE / 社团合影" },
      { src:"assets/projects/ball-astronomy/still-16.jpg", alt:"社员介绍天文台的电脑控制系统", label:"FILM STILL / 控制系统" },
      { src:"assets/projects/ball-astronomy/still-18.jpg", alt:"银河升起在山林上空", label:"ASTROGRAPHY / 星空" }
    ] },
    { id:"lion-go", no:"08", title:"321Lion go", year:"2026", category:"authored", relation:"主动记录 / 团队群像", type:"运动人物微纪录片", role:"导演 / 摄影 / 后期", summary:"记录台湾教练与大陆学生共同备战大学生极限飞盘联赛。\n雨天训练、临场判断与毕业前最后一场主场比赛，共同构成一支队伍关于成长、协作和告别的群像。", result:"入选第二届“光影记·两岸毕业季”网络微纪录片众创分享活动。", link:"https://v.douyin.com/-0kqckWTZl4/", visual:"motion", cover:"assets/projects/lion-go/cover.jpg", media:[] },
    { id:"oxs", no:"09", title:"OXS 欧洲市场产品视觉", year:"2025—2026", category:"commissioned", relation:"品牌合作 / 中国品牌出海 / 德国", type:"游戏与家庭音响产品摄影、短视频与展会动效", role:"创意讨论 / 产品摄影 / 短视频与动效制作", summary:"为中国游戏与家庭音响品牌 OXS 参与面向欧洲消费者的五组产品视觉。\n依据既有品牌规范研究色彩比例、产品可读性与光线层次，完成供品牌评审、独立站、社交媒体与海外展会使用的图片、短视频和动效素材。", result:"完成 5 组产品拍摄与配套内容方案；其中一组动效视频在德国科隆游戏展 OXS 展台实际呈现。部分内容属于提案与备选素材，不表述为全部上线。", link:"https://oxsaudio.com/", linkLabel:"访问品牌网站", visual:"product", cover:"assets/projects/oxs/oxs-01.jpg", media:[
      { src:"assets/projects/oxs/oxs-02.jpg", alt:"OXS 产品影像 02", label:"OXS / PRODUCT STILL 02" },
      { src:"assets/projects/oxs/oxs-04.jpg", alt:"OXS 产品影像 04", label:"OXS / PRODUCT STILL 04" },
      { src:"assets/projects/oxs/oxs-06.jpg", alt:"OXS 产品影像 06", label:"OXS / PRODUCT STILL 06" },
      { src:"assets/projects/oxs/oxs-11.jpg", alt:"OXS 产品影像 11", label:"OXS / PRODUCT STILL 11" },
      { src:"assets/projects/oxs/oxs-process-01.jpg", alt:"OXS 产品拍摄现场", label:"OXS / SHOOTING PROCESS 01" },
      { src:"assets/projects/oxs/oxs-process-02.jpg", alt:"OXS 产品影像后期现场", label:"OXS / POST-PRODUCTION 02" },
      { src:"assets/projects/oxs/oxs-gaming-01.jpg", alt:"OXS 游戏音响桌面场景一", label:"OXS GAMING / PRODUCT STILL 01" },
      { src:"assets/projects/oxs/oxs-gaming-02.jpg", alt:"OXS 游戏耳机产品特写", label:"OXS GAMING / PRODUCT STILL 02" },
      { src:"assets/projects/oxs/oxs-gaming-03.jpg", alt:"OXS 游戏桌面完整场景", label:"OXS GAMING / PRODUCT STILL 03" },
      { src:"assets/projects/oxs/oxs-gamescom-germany.jpg", alt:"OXS 在德国科隆游戏展的实际展台效果", label:"OXS / GAMESCOM COLOGNE, GERMANY" }
    ] },
    { id:"cooling-down", no:"10", title:"吹着吹着就凉了", year:"2025", category:"authored", relation:"校园剧组 / 剧情创作", type:"2022 级毕业设计剧情短片", role:"主摄影 / 后期初剪 / 最终调色", summary:"2025 年 10 月完成的 2022 级毕业设计剧情短片。\n项目用于检验剧情摄影中的机位选择、演员走位与镜头连续性，也让我在后期初剪和最终调色中重新处理节奏、情绪与画面统一。", result:"完成 21 分钟剧情短片；完整版通过项目网盘查看。", link:"https://pan.baidu.com/s/1nRCeDq0GBoJLq37VaDBxsg?pwd=jgki", linkLabel:"观看完整版", visual:"cool", cover:"assets/projects/cooling-down/cover-official.jpg", media:[
      { src:"assets/projects/cooling-down/still-02.jpg", alt:"《吹着吹着就凉了》剧照二", label:"FILM STILL / 02" },
      { src:"assets/projects/cooling-down/still-03.jpg", alt:"《吹着吹着就凉了》剧照三", label:"FILM STILL / 03" },
      { src:"assets/projects/cooling-down/still-04.jpg", alt:"《吹着吹着就凉了》剧照四", label:"FILM STILL / 04" },
      { src:"assets/projects/cooling-down/still-05.jpg", alt:"《吹着吹着就凉了》剧照五", label:"FILM STILL / 05" },
      { src:"assets/projects/cooling-down/still-06.jpg", alt:"《吹着吹着就凉了》剧照六", label:"FILM STILL / 06" },
      { src:"assets/projects/cooling-down/still-07.jpg", alt:"《吹着吹着就凉了》剧照七", label:"FILM STILL / 07" },
      { src:"assets/projects/cooling-down/still-08.jpg", alt:"《吹着吹着就凉了》剧照八", label:"FILM STILL / 08" }
    ] },
    { id:"foreign-language", no:"11", title:"外国语学院招生宣传片", year:"2020.07", category:"commissioned", relation:"学院委托 / 后期制作", type:"中英文招生宣传片", role:"后期", summary:"基于前期团队提供的拍摄素材，独立承担中英文招生宣传片的后期制作。\n剪辑围绕学院的国际传播、语言学习与校园生活重新组织信息层级，在两个语言版本中统一人物、教学空间和海丝文旅讲解场景的叙事节奏。", result:"2020 年 7 月完成中英文版本交付；成片文件通过项目网盘查看。", link:"https://pan.baidu.com/s/1pCxYVk6oOslAbtUqXGc0BQ?pwd=hing", linkLabel:"查看项目文件", visual:"language", importance:"secondary", cover:"assets/projects/foreign-language/cover.jpg", media:[] }
  ]
};
